[200~ Malit@Malit MINGW64 ~ $ cd Desktop/Game-Poject/full/AsteroidsFX-master/
Malit@Malit MINGW64 ~/Desktop/Game-Poject/full/AsteroidsFX-master (main)
$  mvn exec:exec --non-recursive
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< dk.sdu.mmmi.cbse:asteroids.jpms >-------------------
[INFO] Building AsteroidsFX 1.0.1-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- exec:3.5.0:exec (default-cli) @ asteroids.jpms ---
org.springframework.context.annotation.internalConfigurationAnnotationProcessor
org.springframework.context.annotation.internalAutowiredAnnotationProcessor
org.springframework.context.event.internalEventListenerProcessor
org.springframework.context.event.internalEventListenerFactory
moduleConfig
game
scoreClient
entityProcessingServiceList
gamePluginServices
postEntityProcessingServices
[plugin] command channel listening on 127.0.0.1:5599 - try: game plugin list
[plugin] watching plugins/ - deleting a jar unloads that plugin; put it back and run 'game plugin load <name>' to restore it
Scoring microservice unreachable (I/O error on POST request for http://localhost:8081/api/score: Connection refused: connect) - will keep retrying quietly every 3s.
[plugin] PlayerBullet: jar removed from plugins/ - unloading
[plugin] Enemy: jar removed from plugins/ - unloading
    [ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: -1 (Exit value: -1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:355)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:253)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:903)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:863)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:454)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access/usr/bin/bash00 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:919)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:285)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:207)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:255)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:201)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:362)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:314)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  07:32 min
[INFO] Finished at: 2026-08-11T16:41:17+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.5.0:exec (default-cli) on project asteroids.jpms: Command execution failed.: Process exited with an error: -1 (Exit value: -1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Malit@Malit MINGW64 ~/Desktop/Game-Poject/full/AsteroidsFX-master (main)
$     git add .
warning: in the working copy of 'Core/src/main/java/dk/sdu/mmmi/cbse/main/Game.java', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Core/src/main/java/dk/sdu/mmmi/cbse/main/PluginFolderWatcher.java', LF will be replaced by CRLF the next time Git touches it

Malit@Malit MINGW64 ~/Desktop/Game-Poject/full/AsteroidsFX-master (main)
$ git commit -m